spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RecipientOperator
    username: Ameena
    password: Ameena
  application:
    name: RecipientOperator
server:
  port: 8082
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: auto
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
